// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiw6XxUtAJckxj2Ee6wPPigkOvwkdR1-g',
    appId: '1:524871713161:web:24d800bcf2a07ae1022158',
    messagingSenderId: '524871713161',
    projectId: 'fuwafuwa-firstapp-468023',
    authDomain: 'fuwafuwa-firstapp-468023.firebaseapp.com',
    storageBucket: 'fuwafuwa-firstapp-468023.firebasestorage.app',
    measurementId: 'G-7M3E6XBVC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIuNZZCn7tMFHl5dFuKabytyJwQJaGa4k',
    appId: '1:524871713161:android:0580fe4172f331fa022158',
    messagingSenderId: '524871713161',
    projectId: 'fuwafuwa-firstapp-468023',
    storageBucket: 'fuwafuwa-firstapp-468023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRaWLCu7ugIuXiD6YyZTdEJ6w6hmI3B3U',
    appId: '1:524871713161:ios:4ff1fbbb4102aa60022158',
    messagingSenderId: '524871713161',
    projectId: 'fuwafuwa-firstapp-468023',
    storageBucket: 'fuwafuwa-firstapp-468023.firebasestorage.app',
    androidClientId: '524871713161-6f30fflemu9cbgckj53rptgfbj89r0ak.apps.googleusercontent.com',
    iosClientId: '524871713161-vlo1mbg9lj63a9j9vfenbf6rv8ugiohg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fuwafuwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRaWLCu7ugIuXiD6YyZTdEJ6w6hmI3B3U',
    appId: '1:524871713161:ios:4ff1fbbb4102aa60022158',
    messagingSenderId: '524871713161',
    projectId: 'fuwafuwa-firstapp-468023',
    storageBucket: 'fuwafuwa-firstapp-468023.firebasestorage.app',
    androidClientId: '524871713161-6f30fflemu9cbgckj53rptgfbj89r0ak.apps.googleusercontent.com',
    iosClientId: '524871713161-vlo1mbg9lj63a9j9vfenbf6rv8ugiohg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fuwafuwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiw6XxUtAJckxj2Ee6wPPigkOvwkdR1-g',
    appId: '1:524871713161:web:80ddfa24d999c5dd022158',
    messagingSenderId: '524871713161',
    projectId: 'fuwafuwa-firstapp-468023',
    authDomain: 'fuwafuwa-firstapp-468023.firebaseapp.com',
    storageBucket: 'fuwafuwa-firstapp-468023.firebasestorage.app',
    measurementId: 'G-VX5B8SY7L9',
  );

}